#production:env
server.port = 9090
logging.level.org.springframework = info
#production specific configuration
#postgre specific configuration
codexdrive.profile.image.path=/home/profile/prod

#custom codexdrive configuration
codexdrive.config.name = Biitu
codexdrive.config.email = dev.codetogether.gmail.com
codexdrive.config.password = root
codexdrive.config.emailExpTime = 47